### ISSUE TITLE
State test fails when using `BLOCKHASH`

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-specs#1500]
I found the issue of at least one of the cases the eels resover reports an error

```
.venv/lib/python3.12/site-packages/requests/models.py:974: in json
    return complexjson.loads(self.text, **kwargs)
/usr/lib/python3.12/json/__init__.py:346: in loads
    return _default_decoder.decode(s)
/usr/lib/python3.12/json/decoder.py:337: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
/usr/lib/python3.12/json/decoder.py:355: in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
E   json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:
tests/frontier/scenarios/test_scenarios.py:257: in test_scenarios
    state_test(env=tx_env, pre=pre, post=post, tx=tx, post_hint=hint)
src/pytest_plugins/filler/filler.py:836: in __init__
    fixture = self.generate(
src/ethereum_test_specs/state.py:188: in generate
    return self.make_state_test_fixture(t8n, fork, eips, self.post_hint)
src/ethereum_test_specs/state.py:139: in make_state_test_fixture
    transition_tool_output = t8n.evaluate(
src/ethereum_clis/transition_tool.py:487: in evaluate
    return self._evaluate_server(t8n_data=t8n_data, debug_output_path=debug_output_path)
src/ethereum_clis/transition_tool.py:314: in _evaluate_server
    output: TransitionToolOutput = TransitionToolOutput.model_validate(response.json())
.venv/lib/python3.12/site-packages/requests/models.py:978: in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
E   requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------
----------------------------------------
Exception occurred during processing of request from ['local', 0]
Traceback (most recent call last):
  File "/usr/lib/python3.12/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "/home/wins/.cache/ethereum-spec-evm-resolver/Cancun/src/ethereum_spec_tools/evm_tools/daemon.py", line 91, in finish_request
    super().finish_request(request, client_address)
  File "/usr/lib/python3.12/socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/usr/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/home/wins/.cache/ethereum-spec-evm-resolver/Cancun/src/ethereum_spec_tools/evm_tools/daemon.py", line 66, in do_POST
    main(args=args, out_file=out_wrapper, in_file=input)
  File "/home/wins/.cache/ethereum-spec-evm-resolver/Cancun/src/ethereum_spec_tools/evm_tools/__init__.py", line 109, in main
    return t8n_tool.run()
           ^^^^^^^^^^^^^^

```

so if a state test uses blockhash opcode it causes pydantic to panic and eels resolver makes issues in the logs.
which is actually we should report an error. if a state test mode uses blockhash opcode it should be a blockchain test as we agreed to remove fake hash caluclations from t8n

**Comment by marioevz** [comment]
This can still be reproduced, and the issue is that the block number zero is not passed on the t8n interface when filling the test.

I argue that if we are using BLOCKHASH, the test should be a Blockchain test, so this behavior is sort of expected.

I agree with Martin that we should not remove opcodes from the state tests due to fuzzing, so the behavior should stay as is, and perhaps we should just pass the block hash history when requesting a state test.

**Comment by holiman** [comment]
> I agree with Martin that we should not remove opcodes from the state tests due to fuzzing, so the behavior should stay as is, and perhaps we should just pass the block hash history when requesting a state test.

Thank you! Just to re-iterate: my server runs millions of testcases, day after day, week after week. If randomly generated code suddenly were to generate false positives, then there'd be no point in keeping it up. So the security would, in a very hands-on matter, lessen.   

> we should just pass the block hash history when requesting a state test.

Myeah, but not when running state test? I don't quite see what the problem is with the current solution which has been in place since ~ 2015 or so, but as long as you please keep random-generated statetests working across the clients I don't have any complaints. Cheers!

**Comment by holiman** [comment]
> otherwise we need to force everyone to maintain hash calculation for state tests according to this formula.

```golang
crypto.Keccak256(fmt.Sprintf("%d", number))
```
So, basicallly, IIRC, that's the complete implementation burden that is forced on maintainers to not delete from their existing code ;-p
