### ISSUE TITLE
Some errors when trying to run `execution-spec-sync`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/execution-specs#380]
### Metadata

 * Python: CPython 3.9.5
 * Operating System: linux
 * Commit: 4d9ef0574ee0e4042dd58d3bf0ad9b28a3051fc3

#### `pip freeze`

```
asn1crypto==1.4.0
cffi==1.15.0
coincurve==15.0.1
ethash==0.5.1a1
-e git+ssh://git@github.com/ethereum/execution-specs.git@4d9ef0574ee0e4042dd58d3bf0ad9b28a3051fc3#egg=ethereum
lmdb==1.2.1
pycparser==2.20
pysha3==1.0.2
```

### What was wrong?

Fresh install with `pip install -e .[optimized]` and running this command: `ethereum-spec-sync --rpc-url=http://127.0.0.1:8545/ --optimized --persist tmp/block-db`

RPC is: `Geth/v1.10.9-stable-eae3b194/linux-amd64/go1.17`

Got this error:

```
Traceback (most recent call last):
  File "/home/pipermerriam/projects/execution-specs/src/ethereum_spec_tools/sync.py", line 206, in __init__
    with open(blocks_path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/block-db/blocks.pickle'
```

And this one

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pipermerriam/projects/execution-specs/src/ethereum_spec_tools/sync.py", line 487, in download
    raise reply
ethereum_spec_tools.sync.RpcError: invalid argument 0: hex string without 0x prefix
```

On the Geth node I see this error:

```
WARN [10-21|10:46:55.158] Served eth_getBlockByNumber              conn=127.0.0.1:56544 reqid=0x100 t="1.661µs"  err="invalid argument 0: hex string without 0x prefix"
```

### How can it be fixed?

:shrug:

**Comment by pipermerriam** [comment]
Using an absolute path results in the same error.

**Comment by pipermerriam** [comment]
Right, removing the `--persist` still leaves me with the second error about hex encodings.
