### ISSUE TITLE
pyt8n issue

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-specs#840]
```
Request: test_mineBlocks
Alloc:
{
    "0x095e7baea6a6c7c4c2dfeb977efac326af552d87" : {
        "balance" : "0x0de0b6b3a7640000",
        "code" : "0x600160010160005500",
        "nonce" : "0x00",
        "storage" : {
        }
    },
    "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba" : {
        "balance" : "0x00",
        "code" : "0x",
        "nonce" : "0x01",
        "storage" : {
        }
    },
    "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b" : {
        "balance" : "0x0de0b6b3a7640000",
        "code" : "0x",
        "nonce" : "0x00",
        "storage" : {
        }
    }
}
Txs:
"0xf865f863800a83061a8094095e7baea6a6c7c4c2dfeb977efac326af552d87830186a0801ba0ffb600e63115a7362e7811894a91d8ba4330e526f22121c994c4692035dfdfd5a06198379fcac8de3dbfac48b165df4bf88e2088f294b61efb9a65fe2281c76e16"
{
    "data" : "0x",
    "gasLimit" : "0x061a80",
    "gasPrice" : "0x0a",
    "nonce" : "0x00",
    "to" : "0x095e7baea6a6c7c4c2dfeb977efac326af552d87",
    "value" : "0x0186a0",
    "v" : "0x1b",
    "r" : "0xffb600e63115a7362e7811894a91d8ba4330e526f22121c994c4692035dfdfd5",
    "s" : "0x6198379fcac8de3dbfac48b165df4bf88e2088f294b61efb9a65fe2281c76e16"
}
Env:
{
    "currentCoinbase" : "0x2adc25665018aa1fe0e6bc666dac8fc2697ff9ba",
    "currentNumber" : "0x01",
    "currentTimestamp" : "0x03e8",
    "currentGasLimit" : "0xff112233445566",
    "previousHash" : "0x7d46f90648e1c009b83cdec706549090f3676e92fb0ca3cb85de687b73148e13",
    "parentTimestamp" : "0x00",
    "parentDifficulty" : "0x020000",
    "parentUncleHash" : "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
    "blockHashes" : {
        "0" : "0x7d46f90648e1c009b83cdec706549090f3676e92fb0ca3cb85de687b73148e13"
    }
}
```

pyt8n log:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/wins/Ethereum/execution-specs/src/ethereum_spec_tools/evm_tools/__init__.py", line 7, in <module>
    from .b11r import B11R, b11r_arguments
  File "/home/wins/Ethereum/execution-specs/src/ethereum_spec_tools/evm_tools/b11r/__init__.py", line 13, in <module>
    from ..utils import get_stream_logger
  File "/home/wins/Ethereum/execution-specs/src/ethereum_spec_tools/evm_tools/utils.py", line 15, in <module>
    from ..forks import Hardfork
ImportError: attempted relative import beyond top-level package
/home/wins/.retesteth/pyt8n/start.sh --state.fork Berlin --state.reward 0 --state.chainid 1 --input.alloc /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf/alloc.json --input.txs /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf/txs.rlp --input.env /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf/env.json --output.basedir /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf --output.result out.json --output.alloc outAlloc.json --output.errorlog /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf/error.json
Tool Error:
```

```
Response test_mineBlocks: The command '/home/wins/.retesteth/pyt8n/start.sh --state.fork Berlin --state.reward 0 --state.chainid 1 --input.alloc /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf/alloc.json --input.txs /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf/txs.rlp --input.env /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf/env.json --output.basedir /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf --output.result out.json --output.alloc outAlloc.json --output.errorlog /dev/shm/487d1405-ed11-4434-b9d2-55c791606edf/error.json' exited with 256 code.
```

**Comment by winsvega** [comment]
seems to work now
https://github.com/ethereum/execution-specs/pull/841
